export type OpportunityCategory = 'Internship' | 'Full-Time' | 'Research' | 'Fellowship' | 'Part-Time' | 'Project';

export type Opportunity = {
  id: number;
  created_at: string;
  submitter_email: string | null;
  title: string | null;
  recruiting_body: string | null;
  deadline: string | null;
  jd_link: string | null;
  isRolling: boolean | null;
  role: string | null;
  category: OpportunityCategory | null;
  compensation: string | null;
  duration: string | null;
  eligibility: string | null;
  skills: string[] | null;
  apply_url: string | null;
  jd_storage_path: string | null;
  placecom_notes: string | null;
  work_arrangement: string | null;
  compensation_type: string | null;
  duration_weeks: string | null;
  start_date: string | null;
  job_description: string | null;
  eligibility_restrictions: string | null;
  apply_method: string | null;
  is_active: boolean;
  archived_at: string | null;
};
