import type { Opportunity } from "./opportunity-listing";

export const OPPORTUNITIES: Opportunity[] = [
    {
        id: "opp-1",
        name: "Summer Analyst Internship",
        company: "Goldman Sachs",
        role: "Business Analyst",
        category: "Internship",
        deadline: "March 31, 2025",
        compensation: "₹80,000 / month",
        duration: "10 weeks",
        eligibility: "3rd & 4th year UG students",
        skills: ["Excel", "Financial Modelling", "Communication", "PowerPoint"],
        jdUrl: "https://example.com/jd-1",
        applyUrl: "https://example.com/apply-1",
    },
    {
        id: "opp-2",
        name: "Research Fellow – AI & Society",
        company: "Centre for Policy Research",
        role: "Research Fellow",
        category: "Fellowship",
        deadline: "April 15, 2025",
        compensation: "Stipend ₹25,000 / month",
        duration: "3 months",
        eligibility: "Open to all Ashoka students",
        skills: ["Research", "Writing", "Qualitative Analysis", "Policy"],
        jdUrl: "https://example.com/jd-2",
        applyUrl: "https://example.com/apply-2",
    },
    {
        id: "opp-3",
        name: "Software Engineering Intern",
        company: "Microsoft India",
        role: "SWE Intern",
        category: "Internship",
        deadline: "April 5, 2025",
        compensation: "₹1,00,000 / month",
        duration: "2 months",
        eligibility: "CS / Math students with coding background",
        skills: ["Python", "Data Structures", "Algorithms", "SQL", "Git"],
        jdUrl: "https://example.com/jd-3",
        applyUrl: "https://example.com/apply-3",
    },
    {
        id: "opp-4",
        name: "Public Policy Consulting Associate",
        company: "Dalberg Advisors",
        role: "Associate Consultant",
        category: "Full-Time",
        deadline: "April 20, 2025",
        compensation: "Market Linked",
        duration: "Full-time permanent",
        eligibility: "Graduating batch (2025)",
        skills: ["Consulting", "Data Analysis", "Stakeholder Engagement", "Writing"],
        jdUrl: "https://example.com/jd-4",
        applyUrl: "https://example.com/apply-4",
    },
    {
        id: "opp-5",
        name: "UX Design Intern",
        company: "Razorpay",
        role: "Product Designer",
        category: "Internship",
        deadline: "March 28, 2025",
        compensation: "₹50,000 / month",
        duration: "6 weeks",
        eligibility: "Any year, design portfolio required",
        skills: ["Figma", "User Research", "Prototyping", "Visual Design"],
        jdUrl: "https://example.com/jd-5",
        applyUrl: "https://example.com/apply-5",
    },
];
